### ISSUE TITLE
App icons are out of the folder

### ISSUE THREAD

**Issue by mastercreeper66** [Burrit0z/cartella#2]
![image](https://user-images.githubusercontent.com/31628599/75576656-aaf89700-5a60-11ea-85d2-c8be24a8bd0f.png)
When there are many apps in the folder the icons go out of the folder icon

iPhone X iOS 13.3

**Comment by Burrit0z** [comment]
Resize the folder grid icon under visual customization

**Comment by mastercreeper66** [comment]
it wouldn't be possible to leave the 3x3 icon grid in the folder icon? like in bolders

**Comment by Burrit0z** [comment]
Unfortunately, things have changed since iOS 12, and that does cause a crash when exiting folders. I’m looking into a possible workaround.

**Comment by Burrit0z** [comment]
I have figured out how to do this. This feature will be available in the merge folder tweak I am creating with Thomz07, which will be called Folded. It will combine the best aspects of our tweaks together.
