### ISSUE TITLE
Icon Configuration Not Working

### ISSUE THREAD

**Issue by JetsetJoey** [Burrit0z/cartella#6]
I selected four columns by five rows and after respringing, the folders still only contain three columns by three rows. I have tried other configurations, too, but still… Only 3 x 3!

I have an iPhone 11 ProMAX running iOS 13.3.

**Comment by Burrit0z** [comment]
That’s due to another tweak conflict then.

**Comment by Burrit0z** [comment]
Nothing I can do

**Comment by JetsetJoey** [comment]
Hello & thanks for the prompt reply. You were right; HomePlus was interfering with your app, so I deleted it & now Cartella works wonderfully! Great job on a great app!
Ciao~ Joey


Joey J. L'Amarca
Mobile: 1.253.232.5639
CONFIDENTIALITY NOTICE: This e-mail message (including attachments) is covered by the Electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, and is intended only for the person or entity, to which it is addressed, and may contain confidential material. Any unauthorized review, use, disclosure dissemination, copying, forwarding or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and delete all copies of the original message.

________________________________

**Comment by Burrit0z** [comment]
I think HomePlus will have an update soon compatible!

**Comment by JetsetJoey** [comment]
Si, penso cosi... ma parli L'italiano? Anyway, I like Boxy much better than HomePlus, so I think I'll just pay for that.
Ciao ~ Joey


Joey J. L'Amarca
Mobile: 1.253.232.5639
CONFIDENTIALITY NOTICE: This e-mail message (including attachments) is covered by the Electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, and is intended only for the person or entity, to which it is addressed, and may contain confidential material. Any unauthorized review, use, disclosure dissemination, copying, forwarding or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and delete all copies of the original message.

________________________________

**Comment by turtlemaster19** [comment]
@Burrit0z I am having the same issue, but on iPad Pro 1 (Wi-Fi), iPadOS 13.3. I don’t have any other tweaks that I installed:

![5D06C3B4-7CB8-4AEE-9EB4-BEF5273FFAEC](https://user-images.githubusercontent.com/46784000/76534102-0b1b1000-6447-11ea-8daa-b44933d1df10.png)

**Comment by Burrit0z** [comment]
Unfortunately, iPad support is not worked out yet, but is planned in my upcoming tweak with Thomz, Folded

**Comment by turtlemaster19** [comment]
@Burrit0z Thank goodness. I will open an issue so other users know.
