### ISSUE TITLE
Multiple rows and columns

### ISSUE THREAD

**Issue by stephane513** [Burrit0z/cartella#9]
Hello
I tried several ways but I just can’t manage to display more than 3x3 in the folders
Please see my screen shots
![365A0989-3CC3-4295-A9E8-27FEDF34E092](https://user-images.githubusercontent.com/62485139/77236642-c9196900-6bc0-11ea-9848-3175f0802c7c.png)
![ACF3A455-875E-40D5-97E7-6115B4D0E999](https://user-images.githubusercontent.com/62485139/77236650-d171a400-6bc0-11ea-9e93-ccbf6a8a8d1f.png)

**Comment by stephane513** [comment]
Are you please able to super to understand how to setup ?
Thanks in advance

**Comment by Burrit0z** [comment]
That issue would be due to another tweak forcing the configuration to stay in 3x3. Unfortunately, my tweak cannot override that, you must figure out which tweak is doing so. 

Good day to you.

**Comment by stephane513** [comment]
Thanks for you quick answer
I really would want to have that functionality to have more than 3x3
In the past I was so happy with tweaks like folderenhancer 
Your cartella seems really what I am looking
I tried also Foldy but I have similar issues
Can you please look at my tweaks and advise which one could be the cause for the problem ?
Thanks in advance

![D1DDF6EC-F3F8-4A4C-93E5-41FC52020D17](https://user-images.githubusercontent.com/62485139/77245363-53dc8100-6c1e-11ea-8d9b-8d6c86465d17.jpeg)
![97C13085-6697-4F5D-BCF8-23F5D37D460E](https://user-images.githubusercontent.com/62485139/77245364-54751780-6c1e-11ea-947e-471a884ad6dd.jpeg)
![9F3B40D8-DBE1-4BFB-8396-51EBD67A7FA3](https://user-images.githubusercontent.com/62485139/77245365-550dae00-6c1e-11ea-8fd0-f1e2a71ae881.jpeg)

**Comment by stephane513** [comment]
Looking at it it could be the Homeplus but I like the fact to have 7 rows on my screen
Any idea ?

**Comment by Burrit0z** [comment]
Ah, yes homeplus does indeed conflict with Cartella at the moment. Kritanta is going to fix this in his/her next update of homeplus. 

Good day to you.
